version: '3.8' 

services:
  app:
    build: .
    container_name: awtrix-creator-counter
    ports:
      - "4444:4444"
    working_dir: /app
    environment:
      - PORT=4444
      - YOUTUBE_MONEY_EXPORTER_URL={YOUTUBE_MONEY_EXPORTER_URL}
      - AWTRIX_URL={AWTRIX_URL}
    restart: always
    command: npm run start